version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  test_assignment_app:
    build:
      context: .
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
        - STRIPE_PUBLISHABLE_API_KEY=${STRIPE_PUBLISHABLE_API_KEY}
        - STRIPE_SECRET_API_KEY=${STRIPE_SECRET_API_KEY}
    container_name: test_assignment_app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}
      - STRIPE_PUBLISHABLE_API_KEY=${STRIPE_PUBLISHABLE_API_KEY}
      - STRIPE_SECRET_API_KEY=${STRIPE_SECRET_API_KEY}
      - ALLOWED_HOST=${ALLOWED_HOST}
    depends_on:
      postgres:
        condition: service_healthy
